# Machine Learning Zoomcamp


## 1.7 Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/opt/conda/envs/ml-zoomcamp/lib/python3.11/site-packages/numpy/__init__.py'>

## Creating arrays


In [3]:
# Creating arrays the easiest way is to use zeros it takes in the size of the arr you want land fills it with zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# you specify the size and the number you want to fill the arr with in this case we're making 10 2.5s
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,5,7,12]) # converts python list into numpy arr
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2]

np.int64(3)

In [8]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [9]:
np.arange(3,10) # it creates an arr using a range of numbers - excluding the end number

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,100,11) # create an arr using the range in this case and spaces them evenly to the end using the third parameter
# This fu0nction is inclusive of the beginning and the end

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays


In [11]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
# We can also create a 2D arr from a 2d python list
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [13]:
n[0,1] = 20

In [14]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [15]:
n[0]

array([ 1, 20,  3])

In [16]:
n[:,1]

array([20,  5,  8])

In [17]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [18]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

## Randomly generated arrays


In [19]:
np.random.rand(5,2) # generate a 2D array of 5 rows and 2 cols with random number between 0 and 1 from standard uniform distribution

array([[0.47760512, 0.85982389],
       [0.80524711, 0.38883212],
       [0.15803029, 0.41818389],
       [0.66908508, 0.20474816],
       [0.23490091, 0.79083627]])

In [20]:
np.random.seed(2)
100 * np.random.rand(5,2) 
# we also have rand and randn - which gives us random normal i.e. draw numbers from the standard normal distribution

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [21]:
# for random integers we have randint
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations


In [22]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [23]:
a + 1

array([1, 2, 3, 4, 5])

In [24]:
a * 2

array([0, 2, 4, 6, 8])

In [25]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [26]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparison operations

In [27]:
a

array([0, 1, 2, 3, 4])

In [28]:
a >= 2

array([False, False,  True,  True,  True])

In [29]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [30]:
a > b

array([False, False,  True,  True,  True])

In [31]:
a[a > b] # get results from a where a is greater than b

array([2, 3, 4])

## Summarizing operations

In [32]:
a

array([0, 1, 2, 3, 4])

In [33]:
a.std()

np.float64(1.4142135623730951)

In [34]:
a.min()

np.int64(0)

### Next

Linear algebra refresher